"""add ai analysis versioning

Revision ID: 81e845fa54f0
Revises: 1f3f99790db0
Create Date: 2026-09-25 17:15:42.630350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e845fa54f0'
down_revision: Union[str, Sequence[str], None] = '1f3f99790db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_versions',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('root_cause', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('root_cause_analysis', sa.Text(), nullable=False),
    sa.Column('suggested_remediation', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('impact_analysis', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.PrimaryKeyConstraint('analysis_id', 'version')
    )
    op.add_column('ai_analyses', sa.Column('current_version', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'ai_analyses', ['incident_id'])
    op.drop_column('ai_analyses', 'root_cause')
    op.drop_column('ai_analyses', 'suggested_remediation')
    op.drop_column('ai_analyses', 'model')
    op.drop_column('ai_analyses', 'analysis_type')
    op.drop_column('ai_analyses', 'impact_analysis')
    op.drop_column('ai_analyses', 'created_at')
    op.drop_column('ai_analyses', 'confidence')
    op.drop_column('ai_analyses', 'root_cause_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('root_cause_analysis', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('impact_analysis', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('analysis_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('suggested_remediation', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('ai_analyses', sa.Column('root_cause', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_analyses', type_='unique')
    op.drop_column('ai_analyses', 'current_version')
    op.drop_table('ai_analysis_versions')
    # ### end Alembic commands ###
